/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    ColSetting: typeof import('./../components/ProTable/components/ColSetting.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    Grid: typeof import('./../components/Grid/index.vue')['default']
    GridItem: typeof import('./../components/Grid/components/GridItem.vue')['default']
    HButton: typeof import('./../layouts/ui-kit-components/HButton.vue')['default']
    HCheckList: typeof import('./../layouts/ui-kit-components/HCheckList.vue')['default']
    HDialog: typeof import('./../layouts/ui-kit-components/HDialog.vue')['default']
    HDropdown: typeof import('./../layouts/ui-kit-components/HDropdown.vue')['default']
    HDropdownMenu: typeof import('./../layouts/ui-kit-components/HDropdownMenu.vue')['default']
    HInput: typeof import('./../layouts/ui-kit-components/HInput.vue')['default']
    HKbd: typeof import('./../layouts/ui-kit-components/HKbd.vue')['default']
    HSelect: typeof import('./../layouts/ui-kit-components/HSelect.vue')['default']
    HSlideover: typeof import('./../layouts/ui-kit-components/HSlideover.vue')['default']
    HTabList: typeof import('./../layouts/ui-kit-components/HTabList.vue')['default']
    HToggle: typeof import('./../layouts/ui-kit-components/HToggle.vue')['default']
    HTooltip: typeof import('./../layouts/ui-kit-components/HTooltip.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    ImgVerify: typeof import('./../components/ImgVerify/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    Pagination: typeof import('./../components/ProTable/components/Pagination.vue')['default']
    ProTable: typeof import('./../components/ProTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./../components/SearchForm/components/SearchFormItem.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TableColumn: typeof import('./../components/ProTable/components/TableColumn.vue')['default']
  }
}
