name: build

on:
  push:
    branches: [main]
  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

permissions:
  # 允许对仓库的内容进行写操作。包括创建、修改和删除文件、目录以及提交更改等
  # 这里只配置了push，所以只有推送main分支才会触发以下任务
  contents: write
  # 允许管理 GitHub Pages 服务并对其进行写操作
  pages: write

jobs:
  build:
    name: npm 打包
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库信息
        uses: actions/checkout@v4

      - name: 安装依赖和打包
        run: |
          npm i -g pnpm
          pnpm install
          pnpm run build:test

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true # Automatically remove deleted files from the deploy branch
