name: build

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: npm 打包
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库信息
        uses: actions/checkout@v4

      - name: 安装依赖和打包
        run: |
          pnpm install
          pnpm run build:test

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
